### ISSUE TITLE
Feature request: More expressive file globbing

### ISSUE THREAD

**Issue by frenchy64** [haveyoudebuggedit/trojansourcedetector#5]
It would be convenient to specify `**/*.pdf` and or `tmp/**` in exclusions.

**Comment by janosdebugs** [comment]
Hey @frenchy64 I agree that would be desirable. Currently, this is not included because it would need an external library which I tried to avoid. I'll investigate if it can be implemented with relatively minimal effort.

**Comment by frenchy64** [comment]
Thanks!

-------- Original Message --------

**Comment by janosdebugs** [comment]
The fix has now been released in version [1.1.0](https://github.com/haveyoudebuggedit/trojansourcedetector/releases/tag/v1.1.0).
