### ISSUE TITLE
Avoiding non-source files

### ISSUE THREAD

**Issue by patrickdepinguin** [haveyoudebuggedit/trojansourcedetector#7]
I am trying to integrate this tool in a build system like Buildroot, which downloads, extracts and builds various FOSS components.
While just pointing trojansourcedetector to the source directory of each FOSS component, I noticed a lot of false positives due to binary (non-source) files, like images, font files, etc. 

I started using 'exclude' entries in the config file, but having to maintain such list from a generic build system is very cumbersome, as this list may change as FOSS component versions are updated.
For example, here is the exclude list for python3 itself:

        "Doc/library/hashlib-blake2-tree.png",
        "Doc/library/pathlib-inheritance.png",
        "Doc/using/win_installer.png",
        "Lib/distutils/command/wininst-14.0.exe",
        "Lib/ensurepip/_bundled/pip-21.2.3-py3-none-any.whl",
        "Lib/ensurepip/_bundled/setuptools-57.4.0-py3-none-any.whl",
        "Lib/idlelib/Icons/idle_256.png",
        "Lib/idlelib/Icons/idle.ico",
        "Lib/test/audiodata/pluck-pcm24.aiff",
        "Lib/test/audiodata/pluck-pcm24.au",
        "Lib/test/audiodata/pluck-pcm32.aiff",
        "Lib/test/audiodata/pluck-pcm32.au",
        "Mac/BuildScript/resources/background.jpg",
        "Mac/Icons/IDLE.icns",
        "Mac/Icons/PythonCompiled.icns",
        "Mac/Icons/Python Folder.icns",
        "Mac/IDLE/IDLE.app/Contents/Resources/IDLE.icns",
        "Mac/IDLE/IDLE.app/Contents/Resources/PythonCompiled.icns",
        "Mac/Resources/iconsrc/IDE.psd",
        "PC/icons/launcher.icns",
        "PC/icons/pyc.icns",
        "PC/icons/pyd.icns",
        "PC/icons/python.icns",
        "PC/icons/python.ico",
        "PC/icons/pythonw.icns",
        "PC/icons/pythonw.ico",
        "PC/icons/pythonx150.png",
        "PC/icons/setup.icns",
        "Tools/msi/bundle/SideBar.png",

A more expressive glob feature as suggested in issue #5 could perhaps help, but I wonder if there are other approaches.

Can the tool make the distinction between 'source' files and 'binary' files?
A common approach for this is to check for the presence of a null character, but for this case I think it allows for a too easy backdoor for an adversary: adding such null byte in real source code could go unnoticed too.

**Comment by janosdebugs** [comment]
Hey @patrickdepinguin,

I haven't had time to work on it yet, but #5 describes a similar problem. I want to create the possibility to add a ruleset which files to exclude, ideally without introducing dependencies to the project.

I would likely not add a default ruleset, but we could add a set of preconfigured rulesets that people can just easily activate.

**Comment by janosdebugs** [comment]
The fix has now been released in version [1.1.0](https://github.com/haveyoudebuggedit/trojansourcedetector/releases/tag/v1.1.0).
